posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # --- index ---
    url(r'^$', views.index, name='index'),
    url(r'^global_search/$', views.global_search, name='global_search'),

    # --- normal urls, with id ---
    #url(r'^(?P<id>\d+)/$', views.getPostById, name='detail_post'),
    #url(r'^edit/(?P<id>\d+)/$', views.editPost, name='edit_post'),
    #url(r'^delete/(?P<id>\d+)/$', views.deletePost, name='delete_post'),

    url(r'^like/$', views.post_like, name='like'),

    # --- slug urls ---
    # --- function-based views ---
    #url(r'^new/$', views.newPost, name='new_post'),
    url(r'^new/$', views.PostCreateView.as_view(), name='new_post'),

    url(r'^(?P<slug>[\w-]+)/$', views.getPostBySlug, name='detail_post'),

    url(r'^edit/(?P<slug>[\w-]+)/$', views.editPost, name='edit_post'),
    #url(r'^edit/(?P<slug>[\w-]+)/$', views.PostUpdateView.as_view(), name='edit_post'),

    #url(r'^delete/(?P<slug>[\w-]+)/$', views.deletePost, name='delete_post'),
    url(r'^delete/(?P<slug>[\w-]+)/$', views.PostDeleteView.as_view(), name='delete_post'),

    # --- class-based views ---
    #url(r'^$', views.PostListView.as_view(), name='index'),
    #url(r'^(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='detail_post'),

]

profiles/urls.py
from .views import ProfileDetailView, upload_avatar, UserLikesDetailView
from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='user_profile'),
    url(r'^upload/avatar/$', upload_avatar, name='upload_avatar'),
    url(r'^likes/(?P<username>[\w-]+)/$', UserLikesDetailView.as_view(), name='user_likes'),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views

from . import views
from profiles.views import ProfileFollowToggle, activate_user_view

from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^$', views.src_index),

    #url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/login/', views.custom_login, {'template_name':'login.html'}, name='login'),
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^logout/', logout_then_login, name='logout'),

    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),

    url(r'^configuration/', views.ProfileUpdate.as_view(), name='profile_update'),

    url('^change-password/$', auth_views.password_change, {'post_change_redirect' : '/posts/'}, name='password_change'),

    url(r'^reset/password_reset', password_reset, {"template_name": "password_reset_form.html",
        "email_template_name": "password_reset_email.html"}, name="password_reset"),
    url(r'^password_reset_done', password_reset_done, {"template_name":"password_reset_done.html"},
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site

from .utils import code_generator
User = settings.AUTH_USER_MODEL

# Create your models here.
def upload_location(instance, filename):
    username = instance.user.username
    return "avatar/%s/%s_%s" % (username,username, filename)

class ProfileManager(models.Manager):
    def toggle_follow(self, request_user, username_to_toggle):
        profile_ = Profile.objects.get(user__username__iexact=username_to_toggle)
        user = request_user
        is_following = False
        if user in profile_.followers.all():
            profile_.followers.remove(user)
        else:
            profile_.followers.add(user)
            is_following = True
        return profile_, is_following

class Profile(models.Model):
    user = models.OneToOneField(User)
    followers = models.ManyToManyField(User, related_name='is_following', blank=True)
    #following = models.ManyToManyField(User, related_name='following', blank=True)
    activation_key = models.CharField(max_length=120, blank=True, null=True)
    activated = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    avatar = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0, blank=True, null=True)
    width_field = models.IntegerField(default=0, blank=True, null=True)

    objects = ProfileManager()

    def __unicode__(self):
        return self.user.username

    def send_activation_email(self):
        current_site = Site.objects.get_current().domain
        if not self.activated:
            self.activation_key = code_generator()
            self.save()
            path_ = reverse('activate', kwargs={"code": self.activation_key})

            # Send email
            subject = "Activa tu cuenta"
            from_email = settings.DEFAULT_FROM_EMAIL
            message = "Activa tu cuenta aquí: {}".format(path_)
            recipient_list = [self.user.email, ]
            html_message = "<p>Activa tu cuenta aquí: <a href='http://{}{}'>Activation link</a></p>".format(current_site, path_)
            sent_mail = send_mail(subject,
                                  message,
                                  from_email,
                                  recipient_list,
                                  fail_silently=False,
                                  html_message=html_message)
            return sent_mail

    # Override save function so that I can delete images when they are UPDATED
    def save(self, *args, **kwargs):
        # Delete old file when replacing by updating the file
        try:
            this = Profile.objects.get(id=self.id)
            if this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except:
            pass  # When new photo then we do nothing, normal case
        super(Profile, self).save(*args, **kwargs)

def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        # Hago esto para q cualquier usuario nueva q se registre, yo lo siga de
        # manera automatica
        default_user_profile = Profile.objects.get_or_create(user__id=1)[0] # user__username='amos'
        default_user_profile.followers.add(instance)


post_save.connect(post_save_user_receiver, sender=User)

profiles/forms.py
from django import forms

from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "avatar"
        ]

profiles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, View
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.core import serializers

from posts.models import Post
from .models import Profile
from .forms import ProfileForm

# Create your views here.
User = get_user_model()

# Button for following users
class ProfileFollowToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        username_to_toggle = request.POST.get("username")
        profile_, is_following = Profile.objects.toggle_follow(request.user, username_to_toggle)
        return redirect("/profile/{}/".format(profile_.user.username))

# User Profile
class ProfileDetailView(LoginRequiredMixin, DetailView):
    queryset = User.objects.all().filter(is_active=True)
    template_name = 'profiles/profile.html'

    def get_object(self):
        username = self.kwargs.get("username")

        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']

        is_following=False
        if user.profile in self.request.user.is_following.all():
            is_following=True
        context['is_following'] = is_following

        query = self.request.GET.get('q')
        qs = Post.objects.filter(user=user).search(query)
        #if query:
            #qs = qs.search(query) # aqui como se le pasa el usuario busca solo los posts de ese usuario
            #qs = Post.objects.search(query) # aqui como no hay usuario, busca en todos los posts

        if qs.exists():
            context['settings'] = qs
            #context['settings'] = serializers.serialize('json', qs, fields=('title'))
        return context

# User likes
class UserLikesDetailView(LoginRequiredMixin, DetailView):
    queryset = Post.objects.all()
    template_name = 'profiles/profile_likes.html'

    def get_object(self):
        username = self.kwargs.get("username")

        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(UserLikesDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']

        # Filter only the posts that the request.user like
        qs = Post.objects.filter(users_like__in=[user])

        if qs.exists():
            context['settings'] = qs
        return context

# User activation email
def activate_user_view(request, code=None, *args, **kwargs):
    if code:
        qs = Profile.objects.filter(activation_key=code)
        if qs.exists() and qs.count() == 1:
            profile = qs.first()
            if not profile.activated:
                user_ = profile.user
                user_.is_active = True
                user_.save()
                profile.activated = True
                profile.activation_key = None
                profile.save()
                return redirect("login")
    # invalid code
    return redirect("login")

# --------------- Edit User avatar --------------- #
@login_required()
def upload_avatar(request):
    instance = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=instance)

    if request.method == "POST":
        if form.is_valid():
            instance.avatar = request.FILES['avatar']
            print instance.avatar
            instance.save()
            return HttpResponseRedirect(reverse('profiles:user_profile', kwargs={'username': request.user}))

    context = {
        "instance": instance,
        "form": form
    }
    return render(request, 'profiles/upload_avatar.html', context)

profiles/templates/profiles/profile.html
{% extends "posts/base.html" %}

{% block content %}
    {% load staticfiles %}
    <!-- USER PROFILE: AVATAR AND NAME -->
    <div class="row">
        <div class="ag_posts_wrapper col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <div class="row ag_profile_parralax" style="background-image: url('{% static 'posts/img/parallax/parallax3.jpg' %}');">
                <div class="col-md-12 col-sm-12 ag_user_profile_info_block">
                    <div class="row" style="position:relative; display:inline-block;">
                        <div class="col-md-12 col-sm-12 info_block_avatar">
                            <div class="info_block_avatar_radius">
                                <div class="info_block_avatar_image">
                                    {% if user.profile.avatar %}
                                        <img src="{{ user.profile.avatar.url }}" alt="User Image" />
                                    {% else %}
                                        <img src="{% static 'posts/img/favicon/fav.png' %}" alt="User Image" />
                                    {% endif %}
                                </div>
                                {% if user.username == request.user.username %}
                                    <!-- Button for upload the image avatar -->
                                    <a href="#open-modal"><button class="ag_button_upload_image_avatar">UPLOAD</button></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 info_block_user_name">
                            <span>{{ user.get_full_name|title }}</span>
                        </div>
                    </div>

                    {% if user.username != request.user.username %}
                        {% include "profiles/snippet/follow_form.html" with username=user.username is_following=is_following %}
                    {% endif %}

                </div>
            </div>

            <!-- Search form -->
            <!--<form class="form" method="GET" action="" class="ag_form_profile_user_search">
                <input type="text" placeholder="Search..." name="q" value="{{ request.GET.q }}">
                <button type="submit" class="btn btn-default" type="submit">Submit</button>
            </form>-->

            <div id="open-modal" class="modal-window">
                <div>
                    <a href="#modal-close" title="Close" class="modal-close">Close</a>
                    <h1>Actualiza tu avatar</h1>
                    <div>
                        {% if user.username == request.user.username %}
                            <a href="{% url 'profiles:upload_avatar' %}">Modificar</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- USER POSTS -->
    <div class="row">
        <div class="ag_profile_block_posts_by_user col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <div class="ag_profile_block_posts_title">
                POSTS POR {{ user.username|upper }}
            </div>
        </div>
    </div>

    {% if settings %}
        {% for post in settings %}
            <div class="row">
                <div class="ag_profile_block_posts_by_content col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                    <div class="ag_profile_block_posts_by_content_inner">
                        {% if post.image %}
                            <div style="background-image: url('{{ post.image.url }}');" class="ag_prof_inner_image"></div>
                        {% endif %}
                        <div class="ag_prof_inner_content">
                            <div class="ag_prof_inner_title_post">
                                {{ post.title }}
                            </div>
                            <div class="ag_prof_inner_content_post">
                                {{ post.content|truncatewords:20|safe }}
                            </div>
                            <a class="ag_prof_inner_link" href="{{ post.get_absolute_url }}"></a>
                            <div class="ag_prof_inner_user_options">
                                <div class="user_options_like_comment">
                                    <div class="user_options_del_edit">
                                        {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                                            <div class="user_opt_likes">
                                                <i class="fa fa-heart" aria-hidden="true"></i>
                                                <span class="ag_div_likes_number">{{ total_likes }}</span>
                                            </div>
                                        {% endwith %}
                                        <div class="user_opt_comments">
                                            <img class="ag_posts_comment_image" src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                                            <span>{{ post.comments.count }}</span>
                                        </div>
                                    </div>
                                </div>
                                {% if user.username == request.user.username %}
                                    <div class="user_options_del_edit">
                                        <div class="user_opt_edit">
                                            <a href="{% url "posts:edit_post" slug=post.slug %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        </div>
                                        <div class="user_opt_del">
                                            <a href="{% url "posts:delete_post" slug=post.slug %}"><i class="fa fa-times" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="ag_profile_block_posts_by_content col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                <div class="ag_profile_block_posts_by_content_inner">
                    {% if user.username == request.user.username %}
                        <a href="{% url 'posts:new_post' %}">
                            <i class="fa fa-plus-circle"></i>
                            ESCRIBE UN POST
                        </a>
                    {% else %}
                        Este usuario no ha escrito aún ningún post.
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

profiles/templates/profiles/profile_likes.html
{% extends "posts/base.html" %}

{% block content %}
    {% load staticfiles %}

    <!-- USER LIKES -->
    <div class="row">
        <div class="ag_profile_block_posts_by_user col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <div class="ag_profile_block_posts_title">
                POSTS QUE LE GUSTAN A {{ user.username|upper }}
            </div>
        </div>
    </div>

    {% if user.username != request.user.username %}
        {% if user.profile in request.user.is_following.all %}

            {% if settings %}
                {% for post in settings %}

                    <div class="row">
                        <div class="ag_profile_block_posts_by_content col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                            <div class="ag_profile_block_posts_by_content_inner">
                                {% if post.image %}
                                    <div style="background-image: url('{{ post.image.url }}');" class="ag_prof_inner_image"></div>
                                {% endif %}
                                <div class="ag_prof_inner_content">
                                    <div class="ag_prof_inner_title_post">
                                        {{ post.title }}
                                    </div>
                                    <div class="ag_prof_inner_content_post">
                                        {{ post.content|truncatewords:20|safe }}
                                    </div>
                                    <a class="ag_prof_inner_link" href="{{ post.get_absolute_url }}"></a>
                                    <div class="ag_prof_inner_user_options">
                                        <div class="user_options_like_comment">
                                            <div class="user_options_del_edit">
                                                {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                                                    <div class="user_opt_likes">
                                                        <i class="fa fa-heart" aria-hidden="true"></i>
                                                        <span class="ag_div_likes_number">{{ total_likes }}</span>
                                                    </div>
                                                {% endwith %}
                                                <div class="user_opt_comments">
                                                    <img class="ag_posts_comment_image" src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                                                    <span>{{ post.comments.count }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% endif %}

        {% else %}

            <div class="row">
                <div class="ag_profile_block_posts_by_content col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                    <div class="ag_profile_block_posts_by_content_inner">
                        Para poder ver los posts favoritos de este usuario debes <a class="follow_user_favourites" href="/profile/{{ user.username }}/"> seguirle</a>
                    </div>
                </div>
            </div>

        {% endif %}

    {% else %}

        {% if settings %}
            {% for post in settings %}

                <div class="row">
                    <div class="ag_profile_block_posts_by_content col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                        <div class="ag_profile_block_posts_by_content_inner">
                            {% if post.image %}
                                <div style="background-image: url('{{ post.image.url }}');" class="ag_prof_inner_image"></div>
                            {% endif %}
                            <div class="ag_prof_inner_content">
                                <div class="ag_prof_inner_title_post">
                                    {{ post.title }}
                                </div>
                                <div class="ag_prof_inner_content_post">
                                    {{ post.content|truncatewords:20|safe }}
                                </div>
                                <a class="ag_prof_inner_link" href="{{ post.get_absolute_url }}"></a>
                                <div class="ag_prof_inner_user_options">
                                    <div class="user_options_like_comment">
                                        <div class="user_options_del_edit">
                                            {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                                                <div class="user_opt_likes">
                                                    <i class="fa fa-heart" aria-hidden="true"></i>
                                                    <span class="ag_div_likes_number">{{ total_likes }}</span>
                                                </div>
                                            {% endwith %}
                                            <div class="user_opt_comments">
                                                <img class="ag_posts_comment_image" src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                                                <span>{{ post.comments.count }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% endif %}

    {% endif %}



{% endblock %}

profiles/templates/profiles/upload_avatar.html
{% extends "posts/base.html" %}
{% block content %}


        <div class="ag_auth_page_register">
            <div class="input-group update_file_image_div">
                <form class="ag_form_auth_register" method="post" enctype="multipart/form-data" action="{% url 'profiles:upload_avatar' %}">
                    {% csrf_token %}
                    {{ form }}

                    <div class="ag_form_block_input">
                        <div class="ag_form_inner_wrapper">
                            <input class="ag_register_form_submit_button" type="submit" value="Confirm" />
                        </div>
                    </div>
                </form>
            </div>
        </div>


{% endblock %}