posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # --- index ---
    url(r'^$', views.index, name='index'),
    url(r'^global_search/$', views.global_search, name='global_search'),

    # --- normal urls, with id ---
    #url(r'^(?P<id>\d+)/$', views.getPostById, name='detail_post'),
    #url(r'^edit/(?P<id>\d+)/$', views.editPost, name='edit_post'),
    #url(r'^delete/(?P<id>\d+)/$', views.deletePost, name='delete_post'),

    url(r'^like/$', views.post_like, name='like'),

    # --- slug urls ---
    # --- function-based views ---
    #url(r'^new/$', views.newPost, name='new_post'),
    url(r'^new/$', views.PostCreateView.as_view(), name='new_post'),

    url(r'^(?P<slug>[\w-]+)/$', views.getPostBySlug, name='detail_post'),

    url(r'^edit/(?P<slug>[\w-]+)/$', views.editPost, name='edit_post'),
    #url(r'^edit/(?P<slug>[\w-]+)/$', views.PostUpdateView.as_view(), name='edit_post'),

    #url(r'^delete/(?P<slug>[\w-]+)/$', views.deletePost, name='delete_post'),
    url(r'^delete/(?P<slug>[\w-]+)/$', views.PostDeleteView.as_view(), name='delete_post'),

    # --- class-based views ---
    #url(r'^$', views.PostListView.as_view(), name='index'),
    #url(r'^(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='detail_post'),

]

profiles/urls.py
from .views import ProfileDetailView, upload_avatar, UserLikesDetailView
from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='user_profile'),
    url(r'^upload/avatar/$', upload_avatar, name='upload_avatar'),
    url(r'^likes/(?P<username>[\w-]+)/$', UserLikesDetailView.as_view(), name='user_likes'),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views

from . import views
from profiles.views import ProfileFollowToggle, activate_user_view

from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^$', views.src_index),

    #url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/login/', views.custom_login, {'template_name':'login.html'}, name='login'),
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^logout/', logout_then_login, name='logout'),

    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),

    url(r'^configuration/', views.ProfileUpdate.as_view(), name='profile_update'),

    url('^change-password/$', auth_views.password_change, {'post_change_redirect' : '/posts/'}, name='password_change'),

    url(r'^reset/password_reset', password_reset, {"template_name": "password_reset_form.html",
        "email_template_name": "password_reset_email.html"}, name="password_reset"),
    url(r'^password_reset_done', password_reset_done, {"template_name":"password_reset_done.html"},
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from tinymce.models import HTMLField

from .utils import unique_slug_generator
from .validators import validate_title
from django.core.validators import MaxLengthValidator

User = settings.AUTH_USER_MODEL

# Create your models here.
def upload_location(instance, filename):
    first_word = instance.title.split(' ', 1)[0]
    username = instance.user.username
    return "posts/%s/%s_%s" % (username, first_word, filename)

# Methods for the search form
class PostQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            query = query.strip()
            return self.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(title__iexact=query)|
                Q(content__iexact=query)
            )
        return self

class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

#--------------------------------------------------------------------#
##------------------------- POSTS ---------------------##
#--------------------------------------------------------------------#
class Post(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=250, validators=[validate_title])
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0, blank=True, null=True)
    width_field = models.IntegerField(default=0, blank=True, null=True)
    content = HTMLField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    users_like = models.ManyToManyField(User, related_name='posts_liked', blank=True)

    objects = PostManager()

    class Meta:
        ordering = ["-created", "-updated"]
        verbose_name_plural = 'Posts'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail_post", kwargs={"slug": self.slug})

    # Override save function so that I can delete images when they are UPDATED
    def save(self, *args, **kwargs):
        # Delete old file when replacing by updating the file
        try:
            this = Post.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except: pass # When new photo then we do nothing, normal case
        super(Post, self).save(*args, **kwargs)

#--------------------------------------------------------------------#
##------------------------- COMMENTS ---------------------##
#--------------------------------------------------------------------#
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post, related_name="comments")
    contenido = models.TextField(help_text='La longitud máxima del comentario es de 300 caracteres', max_length=300,
                               blank=False, null=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    active = models.BooleanField(default=True) # field I use to deactivate inappropiate comments

    class Meta:
        ordering = ['-created',]

    def __unicode__(self):
        return 'Comentado por {}'.format(self.user)

# Function that do something before the model is saved => save()
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    # Lo q slugify hace es si el titulo es: coche item 1
    # Lo devuelve como (con los guiones): tesla-item-1
    #instance.slug = slugify(instance.title)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image"
        ]

    # def clean_title(self):
    #     title = self.cleaned_data.get('title')
    #     if len(title) > 120:
    #         raise forms.ValidationError("El titulo no puede contener mas de 120 caracteres.")
    #     return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('contenido',)

posts/templates/posts/ajax_search.html
{% if posts.count > 0 %}
    {% for item in posts %}
        <div class="row ag_post_article">
            <div class="ag_post_left col-md-2">
                {% load staticfiles %}
                <div class="ag_post_avatar">
                    <!-- Tiene que ser 40x40px -->
                    {% if item.user.profile.avatar %}
                        <img class="ag_post_avatar_img" src="{{ item.user.profile.avatar.url }}" alt="User Avatar" />
                    {% else %}
                        <img class="ag_post_avatar_img" src="{% static 'posts/img/favicon/fav.png' %}" alt="User Avatar" />
                    {% endif %}
                </div>
            </div>
            <div class="ag_post_right col-md-10">
                <div class="row ag_post_header">
                    <div class="row">
                        <div class="col-md-12">
                            <a class="ag_post_user_name" href="/profile/{{ item.user.username }}/">{{ item.user.get_full_name|title }}</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="ag_post_createdAt">
                                {{ item.created|timesince }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row ag_post_body">
                    {# href="{% url "posts:detail_post" slug=item.slug %}" #}
                    <a class="ag_post_link_content" href="{{ item.get_absolute_url }}" target="_blank">
                        <h5 class="ag_post_title">{{ item.title }}</h5>
                        <div class="row ag_post_content">
                            {{ item.content|truncatewords:50|safe }}
                        </div>
                        {% if item.image %}
                            <div class="wrapper_div_image">
                                <div class="row ag_post_image_div">
                                    <div class="ag_post_image_div_progressive">
                                        <img class="ag_post_img img-responsive" src="{{ item.image.url }}" alt="Post image" />
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </a>
                </div>
                <div class="row ag_post_footer">
                    {% with total_likes=item.users_like.count users_like=item.users_like.all %}

                        <a href="{{ item.get_absolute_url }}" target="_blank">
                        <div class="ag_post_likes {% if request.user not in users_like %}{% else %}ag_post_likes_active{% endif %}">
                            <i class="fa fa-heart" aria-hidden="true"></i>
                            <div class="ag_div_likes_number">
                                {{ total_likes }}
                            </div>
                        </div>
                        </a>

                    {% endwith %}
                    <a href="{{ item.get_absolute_url }}" class="ag_post_comments" target="_blank">
                        <img class="ag_posts_comment_image" src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                        {{ item.comments.count }}
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}

{% block content %}
    <div class="row">
        <div class="ag_posts_wrapper col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">

            {% include "posts/list_ajax.html" %}
            {% include "posts/ajax_search.html" %}

            <!-- Pagination
            <div class="pagination ag_pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                        <a href="?page={{ object_list.previous_page_number }}">Anterior</a>
                    {% endif %}

                    <span class="current">
                        Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                    </span>

                    {% if object_list.has_next %}
                        <a href="?page={{ object_list.next_page_number }}">Siguiente</a>
                    {% endif %}
                </span>
            </div>-->
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
             //Pagination ajax
             var page = 1;
             var empty_page = false;
             var block_request = false;

             $(window).scroll(function() {
                 var margin = $(document).height() - $(window).height() - 200;

                 if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
                     block_request = true;
                     page += 1;

                     $.get('?page=' + page, function(data) {
                         if(data == '') {
                             empty_page = true;
                         } else {
                             block_request = false;
                             $('.ag_posts_wrapper').append(data);
                         }
                     });
                 }
             });

            search_url = '{% url "posts:global_search" %}';
            // Global search ajax
            $(".ag_navbar_search_input").keyup(function(){

                $.ajax({
                    type: "POST",
                    url: search_url,
                    data: {
                        'search_text': $(".ag_navbar_search_input").val()
                    },
                    success: searchSuccess,
                    dataType: 'html'
                });

            });
        });

        function searchSuccess(data, textStatus, jqXHR) {
            $('.ag_posts_wrapper').html(data);
        }
    </script>
{% endblock %}

posts/templates/posts/list_comments_ajax.html
{% load staticfiles %}
{% if comments.count > 0 %}
{% for comment in comments %}

    <div class="article_comments_comments">
        <a href="{% url 'profiles:user_profile' username=comment.user.username %}">
            <div class="comment_comment_avatar">
                <div class="comment_comment_avatar_image" style="{% if comment.user.profile.avatar %}background-image: url('{{ comment.user.profile.avatar.url }}');{% else %}background-image: url('{% static 'posts/img/favicon/fav.png' %}');{% endif %}">
                </div>
            </div>
        </a>

        <!-- Body comment -->
        <div class="article_comments_comments_body">
            <div class="article_comments_comments_body_container">
                <div class="article_comments_comments_body_info">
                    <div class="comment_name_user">
                        <a href="{% url 'profiles:user_profile' username=comment.user.username %}">{{ comment.user.get_full_name|title }}</a>
                    </div>
                    <div class="comment_timestamp">{{ comment.created|timesince }}</div>
                </div>

                <div>
                    <div class="comment_comment_content">
                        <div>
                            <p>{{ comment.contenido|linebreaks|safe }}</p>
                        </div>
                    </div>
                </div>

                <!--
                <div class="article_comments_comments_footer_actions">
                    <div class="footer_action_like">
                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                        <div class="count_heart_likes">
                            2
                        </div>
                    </div>
                    <div class="footer_action_reply">
                        Reply
                    </div>
                </div>
                -->
            </div>
        </div>
    </div>

{% endfor %}
{% endif %}

posts/templates/posts/navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top nav-down">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "posts:index" %}">
                {% load staticfiles %}
                <div class="brand_logo_avatar" style="background-image: url('{% static 'posts/img/logo/agor_logo.png' %}');"></div>
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% if request.path == '/posts/' %}class="active"{% endif %}><a href="{% url 'posts:index' %}">Inicio</a></li>
            </ul>

            <!-- Buscador solo aparece cuando esta en inicio -->
            {% if request.path == '/posts/' %}
                <div class="ag_wrapper_general_form_search col-sm-3 col-md-3">
                    <form class="search_form_navbar" method="POST">
                        <input style="background-image: url('{% static 'posts/img/icons/searchicon.png' %}');" type="text" class="ag_navbar_search_input" placeholder="Buscar por post, título..." name="q">
                    </form>
                </div>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'posts:new_post' %}">Write a Post</a></li>
                    <li class="divider-vertical"><a></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.get_full_name|title }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{% url "profiles:user_profile" username=request.user.username %}">
                                    Perfil
                                    <i style="float:right;" class="fa fa-user"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url "profile_update" %}">
                                    Configuración
                                    <i style="float:right;" class="fa fa-cog"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url "profiles:user_likes" username=request.user.username %}">
                                    Favoritos
                                    <i style="float:right;" class="fa fa-heart-o" aria-hidden="true"></i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="{% url "logout" %}">Salir</a></li>
                {% else %}
                    <li>
                        <a href="{% url 'posts:new_post' %}">Comparte tus ideas</a>
                    </li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% block content %}
    {% load staticfiles %}
    {# Flash messages #}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="row">
        <div class="ag_post_article_detail col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
                <div class="ag_article_header col-xs-8 col-xs-offset-2 col-md-8 col-md-offset-2">
                    <div class="ag_article_name_poster">
                        <a href="{% url "profiles:user_profile" username=instance.user.username %}">
                            <div class="ag_article_avatar_image_user">
                                <div class="ag_article_div_image" style="{% if instance.user.profile.avatar %}background-image: url('{{ instance.user.profile.avatar.url }}');{% else %}background-image: url('{% static 'posts/img/favicon/fav.png' %}');{% endif %}"></div>
                            </div>
                            {{ instance.user.get_full_name|title }}
                        </a>
                    </div>
                    <h1>{{ instance.title }}</h1>
                    <div class="ag_article_header_pub_date">
                        <div class="ag_article_timestamps">
                            <small class="ag_pub_date">Publicado {{ instance.created|date:"M d, Y" }}</small>
                            <small class="ag_upadted_at">Última actualización {{ instance.updated|date:"M d, Y" }}</small>
                        </div>
                    </div>
                </div>
            </div>

            {% if instance.image %}
                <div class="row">
                    <div class="ag_article_image_wrapper col-xs-8 col-xs-offset-2 col-md-8 col-md-offset-2">
                        <a href="{{ instance.image.url }}" class="progressive replace">
                            <img src="{{ instance.image.url }}" class="preview" alt="image" />
                        </a>
                        <!-- <img class="ag_article_img img-small" src="{{ instance.image.url }}" alt="Post detail image" /> -->
                    </div>
                </div>
            {% endif %}

            <div class="row">
                <div class="ag_article_content_wrapper col-xs-8 col-xs-offset-2 col-md-8 col-md-offset-2">
                    {{ instance.content|safe }}
                </div>
            </div>

            <!-- FORM FOR COMMENTS -->
            <div class="row">
                <div class="ag_article_comments_wrapper col-xs-8 col-xs-offset-1 col-md-8 col-md-offset-1">
                    <div class="ag_comments_container">
                        <div class="article_comments_thread">
                            <!-- HEAD -->
                            {% if request.user.is_authenticated %}
                                <div class="article_comments_header">
                                    <img src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                                    {% with comments.count as total_comments %}
                                        {% if total_comments == 0 %}
                                            Sé el primero en compartir tu opinión
                                        {% else %}
                                            {{ total_comments }} Comentario{{ total_comments|pluralize }}
                                        {% endif %}
                                    {% endwith %}
                                </div>

                                <!-- FORM -->
                                <div class="article_reply_form">
                                    <div class="reply_form_avatar">
                                        <div class="reply_form_avatar_image" style="{% if user.profile.avatar %}background-image: url('{{ user.profile.avatar.url }}');{% else %}background-image: url('{% static 'posts/img/favicon/fav.png' %}');{% endif %}">
                                        </div>
                                    </div>
                                    <div class="reply_form_inputs">
                                        <form method="post">
                                            {% csrf_token %}
                                            <textarea name="contenido" id="id_contenido" required="" placeholder="Deja un comentario" rows="2" maxlength="300"></textarea>

                                            <div class="reply_footer">
                                                <div class="footer_hint">La longitud máxima del comentario es de 300 caracteres</div>
                                                <div class="footer_actions">
                                                    <input class="footer_input_subm disabled_input" type="submit" value="Enviar" />
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            {% endif %}

                            <!-- USER COMMENTS -->
                            {% include "posts/list_comments_ajax.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Div for likes and comments -->
    <div class="outside_likes_single_post">
        <div class="wrapper_likes_single_post">
            <div class="likes_single_post_engager">
                <div class="engager_avatar_img">
                    <div class="avatar_img_eng" style="{% if instance.user.profile.avatar %}background-image: url('{{ instance.user.profile.avatar.url }}');{% else %}background-image: url('{% static 'posts/img/favicon/fav.png' %}');{% endif %}"></div>
                </div>
                <div class="engager_hint_text">
                    <div class="eng_title">Enjoy this post?</div>
                    <p>Deja un like y un comentario para <strong>{{ instance.user.username|title }}</strong></p>
                </div>
            </div>
            <div class="likes_single_post_action">

                {% with total_likes=instance.users_like.count users_like=instance.users_like.all %}
                    <a href="#" data-id="{{ instance.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like_button">

                        <div class="likes_heart {% if request.user not in users_like %}{% else %}ag_post_likes_active{% endif %}">
                            <i class="fa fa-heart" aria-hidden="true"></i>
                            <div class="number_likes_post_action">
                                {{ total_likes }}
                            </div>
                        </div>

                    </a>
                {% endwith %}

                <a class="comment_link" href="#id_contenido">
                    <img src="{% static 'posts/img/icons/comment.png' %}" alt="Post comments image" />
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
            // When user click on the comment icon show also the submit button for comments
            $(".comment_link").click(function(){
                $(".reply_form_inputs .reply_footer").css("display", "flex");
            });

            $("#id_contenido")
                .click(function() {
                    $(".reply_footer").show();
                    $(".reply_footer").css( "display", "flex" );
                })
                /*.blur(function(){
                    $(".reply_footer").hide();
                })*/
                .keyup(function() {
                    var count = $(this).val().length;
                    count > 0 ? $( ".footer_input_subm" ).removeClass( "disabled_input" ) : $( ".footer_input_subm" ).addClass( "disabled_input" )
            });

            // Ajax LIKES
            $('a.like_button').click(function(e){
                e.preventDefault();
                $.post('{% url "posts:like" %}',
                    {
                        id: $(this).data('id'),
                        action: $(this).data('action')
                    },
                    function(data) {
                        if(data['status'] == 'ok')
                        {
                            var previous_action = $('a.like_button').data('action');

                            //toggle data-action
                            $('a.like_button').data('action', previous_action == 'like' ? 'unlike' : 'like');

                            //toggle link text
                            $('.likes_heart').addClass(previous_action == 'like' ? $('.likes_heart').addClass("ag_post_likes_active") : $('.likes_heart').removeClass('ag_post_likes_active'));

                            //update total likes
                            var previous_likes = parseInt($(".number_likes_post_action").text());
                            $(".number_likes_post_action").text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                            console.log($(".number_likes_post_action").text());
                        }
                    }
                );
            });

            // Ajax pagination comments
            var page = 1;
            var empty_page = false;
            var block_request = false;

            $(window).scroll(function() {
             var margin = $(document).height() - $(window).height() - 200;

             if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
                 block_request = true;
                 page += 1;

                 $.get('?page=' + page, function(data) {
                     if(data == '') {
                         empty_page = true;
                     } else {
                         block_request = false;
                         $('.article_comments_thread').append(data);
                     }
                 });
             }
            });
        });
    </script>
{% endblock %}